"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBarComp from "../components/organisms/NavBarComp";
import CategoryBar from "@/components/molecules/CategoryBar";
import { usePathname } from "next/navigation";
import Footer from "@/components/molecules/Footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Online shopping site in india",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        {pathname !== "/LogIn" && (
          <div className="bg-blue-100">
            <NavBarComp />
            <CategoryBar />
          </div>
        )}
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
