import { Inter } from "next/font/google";
import "./globals.css";
import NavBarComp from "../components/organisms/NavBarComp";
const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Online shopping site in india",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBarComp/>
        {children}
      </body>
    </html>
  );
}
